steps:
- name: 'sglahn/platformio-core:latest'  
  dir: .
  args: ['run']  
artifacts: 
  objects: 
    location: 'gs://batteryswapstation-firmwares/$TAG_NAME'
    paths: 
      - /workspace/.pio/build/esp32doit-devkit-v1/firmware.bin