#steps:
#- name: 'sglahn/platformio-core:latest'  
#  dir: .
#  args: ['run']  
#artifacts: 
#  objects: 
#    location: 'gs://batteryswapstation-firmwares/$TAG_NAME'
#    paths: '/workspace/.pio/build/esp32doit-devkit-v1/firmware.bin'

steps:
  - name: python
    entrypoint: bash
    args:
      - '-c'
      - |
        pip install --upgrade platformio
        pio run
    dir: .
artifacts:
  objects:
    location: 'gs://batteryswapstation-firmwares/$TAG_NAME'
    paths: '/workspace/.pio/build/esp32doit-devkit-v1/firmware.bin'
